### ISSUE TITLE
A repeated typo is causing all of the isIntX definitions to be wrong

### ISSUE THREAD

**Issue by rwaldron** [jasnell/proposal-istypes#12]
I'll only copy isInt8, because they all have the same issue, so no reason to repeat myself: 

> Number.isInt8(arg)
> Returns true if Number.isNumber(arg) is true and arg is an 8-bit signed integer in the range `-2^7 <= arg <= -2^7-1`.

When implemented as shown:

``` js
function isInt8(arg) {
  return (-Math.pow(2, 7)) <= arg <= (-Math.pow(2, 7) - 1);
}

isInt8(255) === false;
isInt8(127) === false;
isInt8(120) === false;
isInt8(1) === false;
isInt8(-1) === false;
```

This can likely be rolled into the fixes for #11, eg: 

Number.isInt8(arg)
1. If Type(_arg_) is Number and _arg_ is an integer in the range -2<sup>7</sup> through 2<sup>7</sup>-1, inclusive, return **true**.
2. Return **false**.

**Comment by rwaldron** [comment]
Note that there are two defects: 
- The incorrect relational operator for the comparison of the lower boundary and arg 
  - For both isInt and isUint
- The negative upper boundary
  - Only isInt

**Comment by jasnell** [comment]
Sigh. Sorry about that. That's what I get for not proofreading

**Comment by rwaldron** [comment]
Don't sweat it! All quick fixes :)
