### ISSUE TITLE
Opinion against certain functions

### ISSUE THREAD

**Issue by Ginden** [jasnell/proposal-istypes#17]
I feel like checks like:

* `isSetIterator`
* `isGeneratorFunction`
* `isMapIterator`
* `isGeneratorObject`
* `isStringIterator`

shouldn't be included in language. Using any of them feels like a code smell for me - these _classes_ doesn't have any meaningful internals. There is no actual difference between any iterator and `StringIterator`. And 

In case of `isGeneratorFunction` it's merely syntax-level distinction - there is no difference between generator and function returning object with the same interface.

**Comment by ljharb** [comment]
If we're going to add brand checking methods, then *everything* needs to be brand checkable.

Since the iterators are distinct objects, there needs to be a cross-realm way to distinguish them.

**Comment by Ginden** [comment]
For me it's encouraging to implement bad practices (because distinction generator/non-generator is merely implementation detail of function) and language shouldn't encourage end users to make such bad.

**Comment by ljharb** [comment]
You can already distinguish those things (https://www.npmjs.com/package/is-generator-function) - this just provides a consistent way to do so.

**Comment by jasnell** [comment]
I have reworked the proposal significantly to move away from the `Is{Type}` pattern and use a more extensible mechanism that aligns well with the existing `typeof` and `Object.is()` patterns. Please take a look at the updated proposal in this repositories readme.
