### ISSUE TITLE
Would `is` and `typeof` be *configurable* properties of `Builtins`?

### ISSUE THREAD

**Issue by bengl** [jasnell/proposal-istypes#18]
I think there are scenarios in which there would be reasons to override/replace these functions.

**Comment by jasnell** [comment]
Yes, they would be configurable and enumerable.

**Comment by pitaj** [comment]
I disagree. I think these functions should be trustworthy in every circumstance.

**Comment by bengl** [comment]
@pitaj Compare with `Reflect`, where everything is configurable.

**Comment by ljharb** [comment]
@pitaj just like everything in JS, if your code runs first, you can get and hold a reference to it.

Almost everything must be configurable, for polyfills and security reasons. There are very few exceptions to that have a remote chance of getting through committee.

**Comment by jasnell** [comment]
Closing as answered :-)
