### ISSUE TITLE
Clarification for `Symbol.isBuiltinDetectable` false behavior

### ISSUE THREAD

**Issue by bengl** [jasnell/proposal-istypes#19]
It looks `obj[Symbol.isBuiltinDetectable] === false` results in `Bultins.typeof(obj) === typeof obj`, but I can't find it explicitly mentioned anywhere.

**Comment by jasnell** [comment]
Yes, that is the case. If the value passed in to `Builtins.typeof()` is not detectable as a built-in, then it returns the value of `typeof value`. I can work on making that a bit clearer in the text.

**Comment by jasnell** [comment]
This has been since refactored...
