### ISSUE TITLE
two-arg `is` applies to prototype chain as well?

### ISSUE THREAD

**Issue by bengl** [jasnell/proposal-istypes#20]
> When called with a single argument, the `Builtins.is()` function returns true if the given value is either a built-in object or has a built-in object within its prototype chain.
 
but

> The `Builtins.is()` function must return `false` if any of the given values are not built-in objects, or are not the same built-in object. (*TODO*: Need a better definition of "same").

The two-argument case, for consistency with the one-argument case, should probably include the "or has a built-in object within its prototype chain" bit.

**Comment by jasnell** [comment]
Yeah, good catch. The two argument version does search the prototype chain also... Essentially, if the two values either are the same built-in, or are descendents of the same built-in, `is()` returns true

**Comment by jasnell** [comment]
this has been since refactored
