### ISSUE TITLE
`[Symbol.builtin]` and `global.Builtins` should be immutable

### ISSUE THREAD

**Issue by pitaj** [jasnell/proposal-istypes#22]
The functions included in this proposal should be trustworthy no matter what, IMO. That means that no code should be able to change the `[Symbol.builtin]` property of an existing object.

I'd go as far as to say that other objects should not be able to claim they are built in, but that excludes the possibility of polyfilling.

**Comment by ljharb** [comment]
from https://github.com/jasnell/proposal-istypes/issues/18#issuecomment-305934922
> just like everything in JS, if your code runs first, you can get and hold a reference to it.
> 
> Almost everything must be configurable, for polyfills and security reasons. There are very few exceptions to that have a remote chance of getting through committee.

**Comment by jasnell** [comment]
Closing as answered
