### ISSUE TITLE
support for built-in functions/methods

### ISSUE THREAD

**Issue by jasnell** [jasnell/proposal-istypes#25]
@ljharb @bengl: Should built-in functions and methods also be supported by this? For instance,

```js
Builtin.is(parseInt, vm.runInNewContext('parseInt'));

Builtin.is(Object.toString, vm.runInNewContext('Object.toString'));
```

This can be accomplished by requiring that such built-in functions be given a `[[Builtin]]` internal slot and a `@@builtin` own property of their own.

Note that passing the builtin function and method to `Builtin.typeof()` (e.g. `Builtin.typeof(parseInt)`) would still just return `'function'`.

**Comment by doodadjs** [comment]
For natives (built-ins), will there still be a way to distinguish between a constructor and a function ?

**Comment by jasnell** [comment]
@doodadjs ... just so I'm clear, are you referring to the difference between `new Foo()` and `Foo()` ?

**Comment by doodadjs** [comment]
Between "new Object()" and Object.hasOwnProperty()

**Comment by ljharb** [comment]
"is constructor" is a very different type of check than this proposal provides; and you can kind of do that now with something like `function hasConstructSlot(x) try { new Proxy(x, { construct() {} }); return true; } catch (e) { return false; } }`.

**Comment by doodadjs** [comment]
I'm talking about natives. But ok.

**Comment by jasnell** [comment]
@doodadjs ok... yeah I get where you're going, but as @ljharb points out that's a very different kind of check. I do think it would be valuable for a function to indicate via a property if it's a constructor or not, but I'd prefer to handle that separately.

**Comment by jasnell** [comment]
@ljharb ... the original question still stands here... should `Builtin.is()` work for builtin functions and methods also?

**Comment by ljharb** [comment]
Yes, I think so.
