### ISSUE TITLE
Suggest rename typeof to typeOf

### ISSUE THREAD

**Issue by azz** [jasnell/proposal-istypes#31]
Currently the following is both invalid syntax and extremely confusing:

```js
const { typeof } = Builtin; // SyntaxError
typeof ([]); // "Array"
```

Why not rename to `typeOf` such that the following is valid and not ambiguous?

```js
const { typeOf } = Builtin;
typeOf([]); // "Array"
```

**Comment by ljharb** [comment]
Makes sense.

**Comment by jasnell** [comment]
I tend to prefer the symmetry of `Builtin.typeof` to `typeof` but concede the point. Renaming is good.
