### ISSUE TITLE
Some points

### ISSUE THREAD

**Issue by zloirock** [jasnell/proposal-istypes#4]
- `Set.isSharedArrayBuffer`?O_o
- At this moment, we haven't (u)int64 in JS, by IEEE754 integers are safe in float representation only up to 2^53, for that we have `Number.isSafeInteger`, so adding `Number.isInt64` and `Number.isUint64` seems wrong.
- Where is `String.isStringIterator`?
- Generator object is not a function, so why `isGeneratorObject` should be in `Function` namespace?
- Adding `isTypedArray` and `is(Int|Uint)(8|16|32|64)Array` methods to `[TypedArray]` (`%TypedArray%`?) seems wrong - `Uint8Array.isTypedArray(float32array)` or `Float32Array.isUint8Array(uint8array)` confuses.
- `Intl` is not a part of ECMA262, so adding methods to it should be a proposal for ECMA402.

**Comment by jasnell** [comment]
- Point one fixed thanks to @addaleax :-)
- Noted. I'd already been considering pulling `isInt64` and `isUint64` back out.
- Can add `isStringIterator` tho I'm not sure we've seen any significant reason to call that one out in Node.js. Not sure there's much of a use case for it.
- Wasn't sure where else to put `isGeneratorObject()`... it could go on `Object` I suppose.
- Agree on the `[TypedArray]` methods. would like to have a better place to hang those off. Perhaps just make them specific... `Uint8Array.isUint8Array(arg)`, `Uint16Array.isUint16Array(arg)` would be best...
- Agree on the `Intl` stuff... wanted to include those here for completeness but can engage with 402 directly on those.

**Comment by jasnell** [comment]
Updated to address this feedback

**Comment by zloirock** [comment]
👍 
- `String.isStringIterator` required for consistancy with other methods.
- `isTypedArray` also should be moved... maybe to `Object`?

**Comment by jasnell** [comment]
Will add `isStringIterator()`. Will deal with the location of `isTypedArray` separately.
