### ISSUE TITLE
cross-context instanceof checks facilitated by Frozen Realms proposal?

### ISSUE THREAD

**Issue by jokeyrhyme** [jasnell/proposal-istypes#6]
You might be interested in this, if you have not already seen it:
- https://github.com/FUDCo/proposal-frozen-realms

This concept of different execution contexts sharing immutable copies of certain globals could be useful for your cross-context check example.

Imagine if iframes in browsers and VM contexts in Node.js were frozen realms such that `global.Date` was the very same constructor across different contexts? This could make `instanceof` or similar proposed checks feasible.

**Comment by jasnell** [comment]
This would certainly make things easier.

**Comment by jasnell** [comment]
I believe the current proposal handles this case.
