### ISSUE TITLE
How does this handle subclasses?

### ISSUE THREAD

**Issue by rwaldron** [jasnell/proposal-istypes#8]
``` js
class List extends Array {}
// List inherited isArray
List.isArray(new List()) === true;
```

Without any additional language, this will be the case for all of the methods defined in this proposal. I'm just looking for an acknowledgement that this is the intention or not—I presently have no opinion whether or not that's the right thing across the board, that will take time to consider.

**Comment by jasnell** [comment]
The short answer, yes. The longer answer is: this is largely unintentional in that this was not specifically a design goal but it's recognized that this would be the case... (hopefully that makes sense).

**Comment by rwaldron** [comment]
>  (hopefully that makes sense).

It does!
